### ISSUE TITLE
20231012: Orte: popups can no longer be closed in the map

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/stadtgeschichtebasel.ch#17]
**Describe the bug**
When clicking on a marker in the map, the popup can no longer be closed

**To Reproduce**

1. Go to 'Orte'
2. Click on a Marker in the Map
3. Click on another Marker

**Expected behavior**
The popup should close by clicking next to it or on another marker

**Desktop (please complete the following information):**
- Browser: firefox
- Version: latest

**Additional context**
See: /dimfeld/svelte-maplibre#77

**Comment by maehr** [comment]
Thanks for reporting this issue. A fix is ready to merge with the dependency upstream https://github.com/dimfeld/svelte-maplibre/pull/78
