### ISSUE TITLE
Revision of README

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/stadtgeschichtebasel.ch#21]
[Readme.md](https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch/blob/b391acb898c66441ea73b18bb2111ce21a440a2a/README.md) needs a revision.
Especially the necessary command ``pnpm run prebuild`` in the usage section is missing.

**Comment by maehr** [comment]
Is there anything else that needs to be documented?
