### ISSUE TITLE
feat: change mapping-library and improve map layout

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/stadtgeschichtebasel.ch#29]
**Is your feature request related to a problem? Please describe.**
- Svelte-maplibre, which is currently used for the map, is still very rudimentary at the moment. 
- Sometimes the labels on the map overlap. This happens because there are a few locations that are very close together:

![Image](https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch/assets/73133626/de721b03-92cf-45b9-a64c-63a12584d30f)

**Describe the solution you'd like**
- Maplibre-gl can be used directly, so that the full range of functions can be used. At the same time, the map layout can be improved.

- The clusters should be improved and it should be considered if instead of the big "text markers", symbols + a label should be used:

![Image](https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch/assets/73133626/4f1c97d0-78aa-4fc3-8873-757dd6567051)

**Describe alternatives you've considered**
Keep svelte-maplibre

**Additional context**
\-

**Comment by maehr** [comment]
@koilebeit Thanks for the issue. The images are not visible, can you please reupload them?
