### ISSUE TITLE
20131004: links do not lead to corresponding heading (Startseite)

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/stadtgeschichtebasel.ch#7]
**Describe the bug**
The links in the text on "Startseite" do not lead to the corresponding heading on "Meilensteine".

**To Reproduce**

1. Go to "Startseite".
2. Click on link 'Vermittlungsangebote' in the first paragraph.
3. Observe that the link leads to the top of the page "Meilensteine".

**Expected behavior**
The link should lead to the heading 'Vermittlung' on the page "Meilensteine".

**Screenshots**

**Desktop (please complete the following information):**

- OS: Kubuntu
- Browser: firefox
- Version: latest

**Smartphone (please complete the following information):**

**Additional context**
This applies to all links in this paragraph (except for the link "Forschung", which leads to the page "Forschung" instead of "Meilensteine").

**Comment by maehr** [comment]
Somehow the problem does not occur locally but only in deployment. We need to investigate further.
