### ISSUE TITLE
blog: bug in responsive design

### ISSUE THREAD

**Issue by koilebeit** [Stadt-Geschichte-Basel/stadtgeschichtebasel.ch#80]
### Current Behavior

There is a small bug in the responsive design on the blog page:
![Screenshot_20240213_165610](https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch/assets/73133626/fdb0f2c4-9284-42fe-8c12-11ccdc22f356)

### Anything else?

Would it also perhaps better if the mobile version also had a minimal gray border around the images? Otherwise it looks a bit strange if an image has a white background:
![Screenshot_20240213_165734](https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch/assets/73133626/1dd38089-dab6-4cd1-ad70-4f6b3537117b)

**Comment by mtwente** [comment]
@koilebeit The issue of the images with white backgrounds should be solved with the layout tweaks that follow the updated colour scheme per #78
