### ISSUE TITLE
Table with Events Overflowing

### ISSUE THREAD

**Issue by mtwente** [Stadt-Geschichte-Basel/stadtgeschichtebasel.ch#87]
### Current Behavior

On the main page, the table listing upcoming events does not fit on smaller screens, content is overflowing left and right without the possibility to scroll.
![stadtgeschichtebasel ch_(iPhone SE)](https://github.com/Stadt-Geschichte-Basel/stadtgeschichtebasel.ch/assets/127845092/218e5cbc-d3ec-4966-8c4c-174c206433f4)

### Reproduction / Steps To Reproduce

1. Open www.stadtgeschichtebasel.ch on mobile device
2. Scroll to the bottom of the page
3. See table that does not fit on the screen

**Comment by maehr** [comment]
Converted table to list on <https://sgb.hypotheses.org/startseite> to fix this.

**Comment by mtwente** [comment]
I'll add calendar and clock emojis to the list to enhance legibility of the list, cf. the single agenda items on https://stadtgeschichtebasel.ch/agenda
